### ISSUE TITLE
specify ssh port

### ISSUE THREAD

**Issue by atsuya** [1602/roco#1]
Hello,

I just started looking at roco and am wondering if you can specify a port used for ssh. Can you?

**Comment by 1602** [comment]
Sure

## 

Thanks,
Anatoliy

**Comment by 1602** [comment]
Now you can specify `host:port` in hosts var.

Published this feature on v0.0.3

On Thu, Apr 5, 2012 at 12:41 PM, Anatoliy rpm1602@gmail.com wrote:

> Sure
> 
> ## 
> 
> Thanks,
> Anatoliy
> 
> On 05.04.2012, at 11:22, Atsuya Takagi<
> reply@reply.github.com>
> wrote:
> 
> > Hello,
> > 
> > I just started looking at roco and am wondering if you can specify a
> > port used for ssh. Can you?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/1602/roco/issues/1

## 

Thanks,
Anatoliy Chakkaev

**Comment by atsuya** [comment]
awesome! thanks.

**Comment by atsuya** [comment]
forgot to update package.json?
